// Generated by scripts/generate-site-content.js from docs/site-manifest.json.
export const siteContent = {
  navLinks: [
    {
      href: '/',
      label: 'Home',
    },
    {
      href: '/architecture',
      label: 'Architecture',
    },
    {
      href: '/docs',
      label: 'Docs',
    },
    {
      href: 'https://jterrats.dev',
      label: 'Main site',
    },
    {
      href: 'https://github.com/jterrats/smart-deployment',
      label: 'GitHub',
    },
  ],
  hero: {
    eyebrow: 'Salesforce CLI Plugin',
    title: 'Dependency-aware deployment orchestration for Salesforce metadata.',
    lead: 'Smart Deployment is a Salesforce CLI plugin that analyzes metadata, builds deployment waves, validates project state, and executes staged deployments with optional AI assistance.',
    primary: {
      label: 'View Architecture',
      href: '/architecture',
    },
    secondary: {
      label: 'Read Docs',
      href: '/docs',
    },
  },
  commands: [
    {
      name: 'analyze',
      command: 'sf smart-deployment analyze --source-path force-app --use-ai',
      body: 'scans metadata and dependencies; generates deployment waves',
    },
    {
      name: 'validate',
      command: 'sf smart-deployment validate --source-path force-app --use-ai',
      body: 'validates the scanned project structure and generated waves; reports issues and summary data',
    },
    {
      name: 'start',
      command: 'sf smart-deployment start --source-path force-app --target-org myorg',
      body: 'scans metadata; generates waves',
    },
  ],
  operatingModel: {
    eyebrow: 'Operating Model',
    title: 'Analyze first, deploy in controlled waves.',
    steps: ['Scan', 'Graph', 'Plan Waves', 'Validate', 'Deploy'],
  },
  architecture: {
    eyebrow: 'Architecture',
    title: 'Layered deployment planning with explicit side-effect boundaries.',
    lead: 'The plugin keeps parsing, analysis, wave planning, AI inference, and Salesforce CLI execution in separate modules so deployment risk is visible before remote changes begin.',
    layers: [
      {
        title: 'Command Layer',
        body: 'Thin oclif commands parse flags, load configuration, and delegate to services with typed presenters.',
      },
      {
        title: 'Analysis Services',
        body: 'Project scanners, parsers, dependency graph builders, and reporters produce deterministic deployment context.',
      },
      {
        title: 'Wave Engine',
        body: 'Wave builders, validators, splitters, mergers, and remediation planners organize deployable batches.',
      },
      {
        title: 'Execution Services',
        body: 'State managers, Salesforce CLI integration, test planning, retry handling, and reports own runtime effects.',
      },
      {
        title: 'AI Boundary',
        body: 'Provider adapters for Agentforce and OpenAI can assist inference and validation while deterministic fallbacks remain available.',
      },
    ],
    diagram: {
      eyebrow: 'System Diagram',
      title: 'Analysis stays separate from deployment execution.',
      body: 'The command layer coordinates local analysis first. Remote Salesforce effects only happen through the execution services after validation and wave planning.',
      nodes: [
        {
          id: 'cli',
          label: 'Command Layer',
          x: 40,
          y: 90,
        },
        {
          id: 'scan',
          label: 'Metadata Scanners',
          x: 290,
          y: 30,
        },
        {
          id: 'graph',
          label: 'Dependency Graph',
          x: 290,
          y: 150,
        },
        {
          id: 'waves',
          label: 'Wave Engine',
          x: 540,
          y: 90,
        },
        {
          id: 'validate',
          label: 'Validation',
          x: 790,
          y: 30,
        },
        {
          id: 'execute',
          label: 'Execution Services',
          x: 790,
          y: 150,
        },
      ],
      edges: [
        ['cli', 'scan'],
        ['cli', 'graph'],
        ['scan', 'waves'],
        ['graph', 'waves'],
        ['waves', 'validate'],
        ['waves', 'execute'],
      ],
    },
    process: {
      eyebrow: 'Deployment Flow',
      title: 'Analyze, validate, execute, then resume if needed.',
      body: 'Each phase has a durable artifact: graph output, deployment waves, validation findings, deployment state, and final reports.',
      artifacts: [
        'metadata scan',
        'dependency graph',
        'wave plan',
        'validation findings',
        'deployment state',
        'release report',
      ],
    },
    risks: [
      'Circular metadata dependencies',
      'Unsupported parser shapes',
      'AI provider unavailability',
      'Partial wave failure',
      'Large org analysis cost',
    ],
    aiBoundary: {
      eyebrow: 'AI Boundary',
      title: 'Optional inference does not replace deterministic analysis.',
      panels: [
        {
          title: 'Deterministic Core',
          body: 'Parsers, graph algorithms, metadata scanners, and validators produce the baseline deployment plan.',
        },
        {
          title: 'Provider Adapters',
          body: 'Agentforce and OpenAI adapters add prioritization and inference behind explicit configuration.',
        },
      ],
    },
  },
  docs: {
    eyebrow: 'Documentation',
    title: 'Operate Smart Deployment from one place.',
    lead: 'The public docs cover the command surface, AI configuration, known limits, and the architecture boundary that keeps analysis separate from deployment side effects.',
    cards: [
      {
        title: 'Command Reference',
        slug: 'command-reference',
        href: '#command-reference',
        body: 'This reference describes the commands and flags currently implemented in the repository.',
        items: ['--source-path <path>', '--save-plan', '--plan-path <path>'],
      },
      {
        title: 'AI Configuration',
        slug: 'ai-configuration',
        href: '#ai-configuration',
        body: 'The Smart Deployment plugin supports optional AI assistance for:',
        items: ['analyze --use-ai', 'start --use-ai', 'validate --use-ai'],
      },
      {
        title: 'Known Limitations',
        slug: 'known-limitations',
        href: '#known-limitations',
        body: 'This document tracks important current limitations of the Smart Deployment plugin.',
        items: [
          'The command layer is usable, but live deployment coverage against real orgs is still narrower than the local test coverage.',
          'status and resume are driven by persisted local state and are not yet a full remote deployment polling system.',
        ],
      },
      {
        title: 'Release Candidate Checklist',
        slug: 'release-candidate-checklist',
        href: '#release-candidate-checklist',
        body: 'This checklist defines the minimum bar for cutting a release candidate of @jterrats/smart-deployment.',
        items: ['main is green in GitHub Actions', 'yarn test passes locally', 'yarn lint passes locally'],
      },
      {
        title: 'Release Workflow',
        slug: 'release-workflow',
        href: '#release-workflow',
        body: 'This repository uses a single npm publishing workflow:',
        items: [
          'bump=patch|minor|major updates package.json from the current version.',
          'version=x.y.z can be used instead of bump when an exact version is required.',
          'The workflow verifies that the target Git tag and npm version do not already exist.',
        ],
      },
      {
        title: 'Parser Safety',
        slug: 'parser-safety',
        href: '#parser-safety',
        body: 'Salesforce constantly evolves, adding new metadata types, fields, and enum values. Our TypeScript types need to be strict enough for type safety, but flexible enough to handle unknown metadata without breaking.',
        items: [],
      },
    ],
    pages: [
      {
        title: 'Command Reference',
        slug: 'command-reference',
        source: 'docs/cli-reference.md',
        eyebrow: 'Documentation',
        body: 'This reference describes the commands and flags currently implemented in the repository.',
        sections: [
          {
            title: 'sf smart-deployment analyze',
            body: 'Analyze metadata without deploying.',
            items: [
              '--source-path <path>',
              '--save-plan',
              '--plan-path <path>',
              '--use-ai',
              '--org-type <Production|Sandbox|Developer>',
              '--industry <value>',
            ],
          },
          {
            title: 'sf smart-deployment start',
            body: 'Analyze, build waves, and execute deployment.',
            items: [
              '--target-org <org>',
              '--dry-run',
              '--validate-only',
              '--skip-tests',
              '--destructive',
              '--rollback-from <git-ref>',
            ],
          },
          {
            title: 'sf smart-deployment validate',
            body: 'Validate the local wave plan without deploying.',
            items: [
              '--target-org <org>',
              '--source-path <path>',
              '--use-ai',
              'validates the scanned project structure and generated waves',
              'reports issues and summary data',
              'can enrich validation with AI wave analysis',
            ],
          },
          {
            title: 'sf smart-deployment status',
            body: 'Show persisted deployment status.',
            items: [
              '--target-org <org>',
              '--source-path <path>',
              'reads local deployment state',
              'reports current wave, completed waves, remaining waves, and resumability',
              'includes AI metadata when present in state',
            ],
          },
          {
            title: 'sf smart-deployment resume',
            body: 'Resume a failed deployment from persisted local state.',
            items: [
              '--target-org <org>',
              '--source-path <path>',
              '--retry-strategy <standard|quick|validate-only>',
              'loads failed deployment state',
              'rewrites state into a resumed form',
              'prepares the deployment to continue from the failed wave',
            ],
          },
          {
            title: 'sf smart-deployment config',
            body: 'Manage repo-level Smart Deployment configuration.',
            items: [
              '--source-path <path>',
              '--set <key=value>',
              '--get <key>',
              '--get-priority <MetadataType:Name>',
              '--set-priority <MetadataType:Name=priority>',
              '--set-llm-provider <agentforce|openai>',
            ],
          },
        ],
      },
      {
        title: 'AI Configuration',
        slug: 'ai-configuration',
        source: 'docs/ai-configuration.md',
        eyebrow: 'Documentation',
        body: 'The Smart Deployment plugin supports optional AI assistance for:',
        sections: [
          {
            title: 'Supported Providers',
            body: 'The current codebase implements adapters for:',
            items: ['agentforce', 'openai'],
          },
          {
            title: 'Configuration File',
            body: 'Path:',
            items: ['provider', 'model', 'endpoint', 'timeout'],
          },
          {
            title: 'Configure Through The CLI',
            body: 'Set the provider:',
            items: [],
          },
          {
            title: 'AI-Enabled Command Paths',
            body: 'The following flows currently consume repo-level AI config:',
            items: ['analyze --use-ai', 'start --use-ai', 'validate --use-ai', 'provider', 'model', 'fallback status'],
          },
          {
            title: 'Fallback Behavior',
            body: 'AI is optional.',
            items: [],
          },
          {
            title: 'Notes',
            body: '',
            items: [
              'Current docs describe the code as it exists today, not a future provider roadmap.',
              'Older Agentforce-only design docs were archived because the runtime is no longer single-provider.',
            ],
          },
        ],
      },
      {
        title: 'Known Limitations',
        slug: 'known-limitations',
        source: 'docs/known-limitations.md',
        eyebrow: 'Documentation',
        body: 'This document tracks important current limitations of the Smart Deployment plugin.',
        sections: [
          {
            title: 'Deployment Execution',
            body: '',
            items: [
              'The command layer is usable, but live deployment coverage against real orgs is still narrower than the local test coverage.',
              'status and resume are driven by persisted local state and are not yet a full remote deployment polling system.',
            ],
          },
          {
            title: 'Circular Dependency Remediation',
            body: 'See Circular dependency remediation spec for the intended direction.',
            items: [
              'automatic remediation is intentionally conservative',
              'supported scope is currently limited to simple, safely rewritable cycles',
              'unsupported or ambiguous cycles still require manual resolution',
            ],
          },
          {
            title: 'AI Support',
            body: '',
            items: [
              'AI support is optional and can fall back to heuristics',
              'not every product path is equally AI-enriched yet',
              'provider support is still early-stage despite the shared abstraction',
            ],
          },
          {
            title: 'XML Validation',
            body: '',
            items: [
              'the XML metadata validator exists, but it does not yet satisfy the full scope described in the tracked story for richer namespace, fix-up, and integration behavior',
            ],
          },
          {
            title: 'Reporting And Contracts',
            body: '',
            items: [
              'command output is becoming more structured, but the JSON contract should still be treated as evolving',
              'analysis reports are real and written to disk, but broader deployment-reporting semantics are still being hardened',
            ],
          },
          {
            title: 'Historical Docs',
            body: 'Several documents were archived because they described non-existent flags or superseded workflows. If you find references to --ai-auto, --use-plan, --strict, --verify-against-plan, or --max-diff, treat those as historical material, not current product behavior.',
            items: [],
          },
        ],
      },
      {
        title: 'Release Candidate Checklist',
        slug: 'release-candidate-checklist',
        source: 'docs/release-candidate-checklist.md',
        eyebrow: 'Documentation',
        body: 'This checklist defines the minimum bar for cutting a release candidate of @jterrats/smart-deployment.',
        sections: [
          {
            title: 'Entry Criteria',
            body: '',
            items: [
              'main is green in GitHub Actions',
              'yarn test passes locally',
              'yarn lint passes locally',
              'tsc -p ./test --pretty false passes locally',
              'no known failing NUTs on Linux or Windows',
            ],
          },
          {
            title: 'Functional Smoke',
            body: 'Run and verify at least these flows against a fixture Salesforce project:',
            items: [
              'sf smart-deployment analyze --source-path <path>',
              'sf smart-deployment analyze --source-path <path> --save-plan --output analysis.json --format json',
              'sf smart-deployment validate --source-path <path> --json',
              'sf smart-deployment start --source-path <path> --dry-run',
              'sf smart-deployment status --source-path <path>',
              'sf smart-deployment resume --source-path <path> --retry-strategy standard --json',
            ],
          },
          {
            title: 'Packaging',
            body: '',
            items: [
              'npm pack --dry-run succeeds',
              'tarball contains lib/**',
              'tarball contains messages/**',
              'tarball contains oclif.manifest.json',
              'tarball contains oclif.lock',
              'package metadata matches the public repo: - name - version - repository - homepage - bugs - license',
            ],
          },
          {
            title: 'Release Readiness',
            body: '',
            items: [
              'README.md reflects the current command surface',
              'docs/cli-reference.md reflects the current flags',
              'docs/known-limitations.md reflects real remaining gaps',
              'release notes summarize: - supported commands - AI support status - circular remediation scope - known limitations',
            ],
          },
          {
            title: 'NPM Publication Readiness',
            body: '',
            items: [
              'target version does not already exist on npm',
              'NPM_TOKEN has publish permission for @jterrats/smart-deployment',
              'publish-npm.yml is enabled and green on main',
              'release operators follow Release Workflow',
              'npm publication evidence includes package visibility and latest dist-tag verification',
            ],
          },
          {
            title: 'Known Non-Blockers For RC',
            body: 'These do not need to be fully solved before an RC if the rest of the checklist is green:',
            items: [
              'deeper refactors of remaining large core files',
              'richer non-heuristic test selection',
              'broader AI provider ecosystem',
              'broader real-org deployment coverage beyond current smoke scope',
            ],
          },
        ],
      },
      {
        title: 'Release Workflow',
        slug: 'release-workflow',
        source: 'docs/release-workflow.md',
        eyebrow: 'Documentation',
        body: 'This repository uses a single npm publishing workflow:',
        sections: [
          {
            title: 'Prepare a New Release',
            body: 'Run Publish to npm with Provenance manually without a tag input.',
            items: [
              'bump=patch|minor|major updates package.json from the current version.',
              'version=x.y.z can be used instead of bump when an exact version is required.',
              'The workflow verifies that the target Git tag and npm version do not already exist.',
              'The workflow runs install, build, tests, lint, runtime dependency audit, and npm pack --dry-run.',
              'The workflow commits the version bump, creates the annotated tag, creates the GitHub Release, publishes to npm with provenance, verifies npm availability, and checks the latest dist-tag.',
            ],
          },
          {
            title: 'Publish an Existing Tag',
            body: 'Run the same workflow with tag=vX.Y.Z, or publish a GitHub Release for an existing tag.',
            items: [
              'The workflow checks out the tag.',
              'package.json version must match the tag without the v prefix.',
              'The workflow runs install, build, tests, lint, package-content checks, and npm publication.',
              'If the version is already published, npm publish is skipped and the run succeeds as a safe rerun.',
            ],
          },
          {
            title: 'Required Evidence',
            body: 'Every release run should leave evidence for:',
            items: [
              'runtime dependency audit: npm audit --omit=dev --json',
              'pack contents: npm pack --dry-run',
              'version target checks: existing Git tag and npm version',
              'npm publication verification: npm view <package>@<version> version',
              'dist-tag verification: npm view <package> dist-tags.latest',
            ],
          },
          {
            title: 'Safe Rerun Behavior',
            body: 'Rerunning the workflow for an already-published version must not republish the package.',
            items: [
              'The workflow sets already_published=true when npm already has the version.',
              'The publish step is skipped.',
              'Publication verification exits successfully after confirming the version exists.',
              'The latest dist-tag assertion is skipped for already-published reruns because old tags may not be the current latest version.',
            ],
          },
        ],
      },
      {
        title: 'Parser Safety',
        slug: 'parser-safety',
        source: 'docs/PARSER_SAFETY.md',
        eyebrow: 'Documentation',
        body: 'Salesforce constantly evolves, adding new metadata types, fields, and enum values. Our TypeScript types need to be strict enough for type safety, but flexible enough to handle unknown metadata without breaking.',
        sections: [
          {
            title: 'Problem',
            body: 'Salesforce constantly evolves, adding new metadata types, fields, and enum values. Our TypeScript types need to be strict enough for type safety, but flexible enough to handle unknown metadata without breaking.',
            items: [],
          },
          {
            title: 'Risks',
            body: "const flow: FlowMetadata = { processType: 'NewType2025', // ❌ TypeScript error! // ... }; ```",
            items: [],
          },
          {
            title: 'Solution: Two-Tier Type System',
            body: 'Use these when parsing metadata from XML/source:',
            items: [],
          },
          {
            title: 'Usage Patterns',
            body: 'export function parseFlow(xmlContent: string): FlowMetadata { // 1. Parse with permissive types const parsed: ParsedFlowMetadata = { label: extractLabel(xmlContent), processType: extractProcessType(xmlContent), status: extractStatus(xmlContent), };',
            items: [],
          },
          {
            title: 'Best Practices',
            body: '1. Use Parser Types in parsers',
            items: [],
          },
          {
            title: 'Testing Forward Compatibility',
            body: "// ✅ Should NOT throw const flow = parseFlow(xml); expect(flow.processType).to.equal('FutureType2026'); });",
            items: [],
          },
        ],
      },
    ],
    nextStep: {
      eyebrow: 'Recommended Paths',
      title: 'Follow the workflow you are running.',
      panels: [
        {
          title: 'Operate the CLI',
          body: 'Start with the command reference when you need supported flags, behavior, and command differences.',
          label: 'Open command reference',
          href: '#command-reference',
          internal: true,
        },
        {
          title: 'Prepare a release',
          body: 'Use the release checklist and workflow when validating a candidate or publishing the package.',
          label: 'Open release checklist',
          href: '#release-candidate-checklist',
          internal: true,
        },
      ],
    },
  },
} as const;
