/*
 * retryUntil — bounded retry helper for async DML (Queueable / Platform Events).
 * Generated by @jterrats/setup-agents — sf setup-agents local --profile qa
 *
 * Usage:
 *   const cases = await retryUntil(
 *     () => client.query('SELECT Id FROM Case WHERE Subject = \'Test\''),
 *     (rows) => rows.length > 0,
 *     { timeoutMs: 10_000, intervalMs: 500 }
 *   );
 */

export async function retryUntil<T>(
  fn: () => Promise<T>,
  predicate: (value: T) => boolean,
  opts: { timeoutMs: number; intervalMs: number }
): Promise<T> {
  const deadline = Date.now() + opts.timeoutMs;
  let lastValue: T | undefined;
  while (Date.now() < deadline) {
    lastValue = await fn();
    if (predicate(lastValue)) return lastValue;
    await sleep(opts.intervalMs);
  }
  if (lastValue !== undefined && predicate(lastValue)) return lastValue;
  throw new Error(`retryUntil: predicate not satisfied within ${opts.timeoutMs}ms`);
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
