/*
 * SfCliClient — typed Salesforce CLI wrapper for Playwright / E2E tests.
 * Generated by @jterrats/setup-agents — sf setup-agents local --profile qa
 *
 * Usage:
 *   const client = new SfCliClient();                    // uses default org
 *   const client = new SfCliClient('qa-sandbox');        // named alias
 *   const cases  = await client.query<{ Id: string }>('SELECT Id FROM Case');
 *
 * Security: all sf commands use execFileSync with arg arrays — no shell interpolation.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

export class SfCliClient {
  constructor(private targetOrg?: string) {}

  /** Run a SOQL query and return typed rows. */
  async query<T>(soql: string, opts?: { useToolingApi?: boolean; persistToFile?: string }): Promise<T[]> {
    const args = ['data', 'query', '--query', soql, '--json'];
    if (opts?.useToolingApi) args.push('--use-tooling-api');
    if (this.targetOrg) args.push('--target-org', this.targetOrg);
    const raw = execFileSync('sf', args, { encoding: 'utf8', timeout: 30_000 });
    const parsed = JSON.parse(raw) as { result?: { records?: T[] } };
    const records = parsed.result?.records ?? [];
    if (opts?.persistToFile) {
      mkdirSync(dirname(opts.persistToFile), { recursive: true });
      writeFileSync(opts.persistToFile, raw, 'utf8');
    }
    return records;
  }

  /** Run anonymous Apex from a file. */
  async runApex(file: string): Promise<{ success: boolean; logs: string }> {
    const args = ['apex', 'run', '--file', file, '--json'];
    if (this.targetOrg) args.push('--target-org', this.targetOrg);
    try {
      const raw = execFileSync('sf', args, { encoding: 'utf8', timeout: 60_000 });
      const parsed = JSON.parse(raw) as { result?: { success?: boolean; logs?: string } };
      return { success: parsed.result?.success ?? false, logs: parsed.result?.logs ?? '' };
    } catch {
      return { success: false, logs: '' };
    }
  }

  /** Delete a single record by SObject type and Id. */
  async deleteRecord(sobject: string, id: string): Promise<void> {
    const args = ['data', 'delete', 'record', '--sobject', sobject, '--record-id', id, '--json'];
    if (this.targetOrg) args.push('--target-org', this.targetOrg);
    execFileSync('sf', args, { encoding: 'utf8', timeout: 15_000 });
  }
}
