name: Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  yarn-lockfile-check:
    uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@main

  linux-unit-tests:
    needs: yarn-lockfile-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install dependencies
        uses: salesforcecli/github-workflows/.github/actions/retry@main
        with:
          command: yarn install --frozen-lockfile --network-timeout 600000

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

  windows-build-check:
    needs: linux-unit-tests
    runs-on: windows-latest
    steps:
      - name: Enable long paths
        run: git config --system core.longpaths true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install dependencies
        uses: salesforcecli/github-workflows/.github/actions/retry@main
        with:
          command: yarn install --frozen-lockfile --network-timeout 600000

      - name: Build
        run: yarn build

  nuts:
    needs: linux-unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
